

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-website
  namespace: toy-example
  labels:
    release: prometheus-mec
spec:
  selector:
    matchLabels:
      app: website
  endpoints:
  - port: metrics
    interval: 30s

