apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-calls-nginx
  labels:
    app: infinite-calls-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinite-calls-nginx
  template:
    metadata:
      name: infinite-calls-nginx
      labels:
        app: infinite-calls-nginx
    spec:
      containers:
      - name: infinite-calls-nginx
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://my-nginx; done"
        